default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: maikondouglas
  password: 12345678
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_development

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  database: todo_production
  username: todo
  password: <%= ENV["TODO_DATABASE_PASSWORD"] %>
